# config.yaml

seed   : 42
device : 'cuda'

model:
  sam_model_type   : "vit_b"
  sam_checkpoint   : "./checkpoints/sam_vit_b.pth"
  freeze_sam       : True
  decoder_channels : [256, 128, 64, 32]

data:
  use_hf: true                           # true -> stream from HF; false -> local (not used here)
  hf_repo: "saberzl/SID_Set"             # the HF dataset id
  hf_split_train: "train"
  hf_split_val: "validation"
  hf_split_test: "test"                  # change if HF uses a different name
  img_size: 1024
  hf_cache_dir: null   


train:
  epochs: 6
  batch_size: 4                          
  lr: 0.0005
  weight_decay: 0.006
  grad_accum: 1
  amp: true

logging:
  tb_logdir: ./logs
  checkpoint_dir: ./checkpoints/finetuned
  save_every: 1
  example_images_every_n_epochs: 1